/********************************************************************************
** Form generated from reading UI file 'game.ui'
**
** Created by: Qt User Interface Compiler version 6.6.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GAME_H
#define UI_GAME_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_game
{
public:
    QPushButton *QuitBtn;
    QPushButton *QuitAllBtn;
    QPushButton *grid1;
    QPushButton *grid2;
    QPushButton *numOneBtn;
    QPushButton *numTwoBtn;
    QPushButton *numThreeBtn;
    QPushButton *numFourBtn;
    QPushButton *numFiveBtn;
    QPushButton *numSixBtn;
    QPushButton *numSevenBtn;
    QPushButton *numEightBtn;
    QPushButton *numNineBtn;
    QPushButton *submitBtn;
    QPushButton *grid3;
    QPushButton *remErrorsBtn;
    QPushButton *newGameBtn;
    QPushButton *eraseBtn;
    QPushButton *grid4;
    QPushButton *grid5;
    QPushButton *grid6;
    QPushButton *grid7;
    QPushButton *grid8;
    QPushButton *grid9;
    QFrame *verticleLine1;
    QFrame *verticleLine2;
    QPushButton *grid12;
    QPushButton *grid10;
    QPushButton *grid11;
    QPushButton *grid13;
    QPushButton *grid14;
    QPushButton *grid15;
    QPushButton *grid17;
    QPushButton *grid16;
    QPushButton *grid18;
    QPushButton *grid20;
    QPushButton *grid21;
    QPushButton *grid19;
    QPushButton *grid23;
    QPushButton *grid22;
    QPushButton *grid24;
    QPushButton *grid26;
    QPushButton *grid25;
    QPushButton *grid27;
    QFrame *line;
    QFrame *verticleLine2_2;
    QFrame *line_2;
    QPushButton *grid38;
    QPushButton *grid48;
    QPushButton *grid46;
    QPushButton *grid30;
    QPushButton *grid39;
    QPushButton *grid28;
    QPushButton *grid47;
    QPushButton *grid37;
    QPushButton *grid29;
    QPushButton *grid31;
    QPushButton *grid50;
    QPushButton *grid41;
    QPushButton *grid49;
    QPushButton *grid40;
    QPushButton *grid42;
    QPushButton *grid51;
    QPushButton *grid32;
    QPushButton *grid33;
    QPushButton *grid34;
    QPushButton *grid53;
    QPushButton *grid44;
    QPushButton *grid52;
    QPushButton *grid43;
    QPushButton *grid45;
    QPushButton *grid54;
    QPushButton *grid35;
    QPushButton *grid36;
    QFrame *line_3;
    QPushButton *grid56;
    QPushButton *grid65;
    QPushButton *grid55;
    QPushButton *grid64;
    QPushButton *grid74;
    QPushButton *grid66;
    QPushButton *grid57;
    QPushButton *grid73;
    QPushButton *grid75;
    QPushButton *grid77;
    QPushButton *grid67;
    QPushButton *grid58;
    QPushButton *grid78;
    QPushButton *grid69;
    QPushButton *grid59;
    QPushButton *grid68;
    QPushButton *grid76;
    QPushButton *grid60;
    QPushButton *grid61;
    QPushButton *grid63;
    QPushButton *grid72;
    QPushButton *grid80;
    QPushButton *grid79;
    QPushButton *grid70;
    QPushButton *grid71;
    QPushButton *grid81;
    QPushButton *grid62;
    QFrame *verticleLine2_4;
    QFrame *verticleLine2_5;
    QFrame *verticleLine2_6;
    QFrame *verticleLine2_7;
    QFrame *verticleLine2_8;
    QFrame *verticleLine2_10;
    QFrame *verticleLine2_11;
    QFrame *verticleLine2_12;
    QFrame *verticleLine2_13;
    QFrame *verticleLine2_14;
    QFrame *verticleLine2_15;
    QFrame *verticleLine2_16;
    QFrame *verticleLine2_17;
    QFrame *verticleLine2_18;
    QFrame *verticleLine2_19;
    QFrame *verticleLine2_20;
    QFrame *verticleLine2_21;
    QFrame *line_4;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QFrame *line_9;
    QFrame *line_10;
    QFrame *line_11;
    QFrame *line_12;
    QFrame *line_13;
    QFrame *line_14;
    QFrame *line_15;
    QFrame *line_16;
    QFrame *line_17;
    QFrame *line_18;
    QFrame *line_19;
    QFrame *line_20;

    void setupUi(QDialog *game)
    {
        if (game->objectName().isEmpty())
            game->setObjectName("game");
        game->resize(1143, 908);
        QuitBtn = new QPushButton(game);
        QuitBtn->setObjectName("QuitBtn");
        QuitBtn->setGeometry(QRect(980, 90, 111, 41));
        QFont font;
        font.setFamilies({QString::fromUtf8("MV Boli")});
        font.setPointSize(15);
        QuitBtn->setFont(font);
        QuitAllBtn = new QPushButton(game);
        QuitAllBtn->setObjectName("QuitAllBtn");
        QuitAllBtn->setGeometry(QRect(980, 30, 111, 41));
        QuitAllBtn->setFont(font);
        grid1 = new QPushButton(game);
        grid1->setObjectName("grid1");
        grid1->setGeometry(QRect(90, 50, 51, 51));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid1->setPalette(palette);
        QFont font1;
        font1.setPointSize(30);
        grid1->setFont(font1);
        grid1->setAutoFillBackground(true);
        grid1->setAutoDefault(false);
        grid1->setFlat(true);
        grid2 = new QPushButton(game);
        grid2->setObjectName("grid2");
        grid2->setGeometry(QRect(160, 50, 51, 51));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Button, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid2->setPalette(palette1);
        grid2->setFont(font1);
        grid2->setAutoFillBackground(true);
        grid2->setAutoDefault(false);
        grid2->setFlat(true);
        numOneBtn = new QPushButton(game);
        numOneBtn->setObjectName("numOneBtn");
        numOneBtn->setGeometry(QRect(60, 740, 61, 61));
        QFont font2;
        font2.setPointSize(33);
        numOneBtn->setFont(font2);
        numTwoBtn = new QPushButton(game);
        numTwoBtn->setObjectName("numTwoBtn");
        numTwoBtn->setGeometry(QRect(140, 740, 61, 61));
        numTwoBtn->setFont(font2);
        numThreeBtn = new QPushButton(game);
        numThreeBtn->setObjectName("numThreeBtn");
        numThreeBtn->setGeometry(QRect(220, 740, 61, 61));
        numThreeBtn->setFont(font2);
        numFourBtn = new QPushButton(game);
        numFourBtn->setObjectName("numFourBtn");
        numFourBtn->setGeometry(QRect(300, 740, 61, 61));
        numFourBtn->setFont(font2);
        numFiveBtn = new QPushButton(game);
        numFiveBtn->setObjectName("numFiveBtn");
        numFiveBtn->setGeometry(QRect(380, 740, 61, 61));
        numFiveBtn->setFont(font2);
        numSixBtn = new QPushButton(game);
        numSixBtn->setObjectName("numSixBtn");
        numSixBtn->setGeometry(QRect(460, 740, 61, 61));
        numSixBtn->setFont(font2);
        numSevenBtn = new QPushButton(game);
        numSevenBtn->setObjectName("numSevenBtn");
        numSevenBtn->setGeometry(QRect(540, 740, 61, 61));
        numSevenBtn->setFont(font2);
        numEightBtn = new QPushButton(game);
        numEightBtn->setObjectName("numEightBtn");
        numEightBtn->setGeometry(QRect(620, 740, 61, 61));
        numEightBtn->setFont(font2);
        numNineBtn = new QPushButton(game);
        numNineBtn->setObjectName("numNineBtn");
        numNineBtn->setGeometry(QRect(700, 740, 61, 61));
        numNineBtn->setFont(font2);
        submitBtn = new QPushButton(game);
        submitBtn->setObjectName("submitBtn");
        submitBtn->setGeometry(QRect(860, 640, 151, 61));
        QFont font3;
        font3.setPointSize(17);
        submitBtn->setFont(font3);
        grid3 = new QPushButton(game);
        grid3->setObjectName("grid3");
        grid3->setGeometry(QRect(230, 50, 51, 51));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::Button, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid3->setPalette(palette2);
        grid3->setFont(font1);
        grid3->setAutoFillBackground(true);
        grid3->setAutoDefault(false);
        grid3->setFlat(true);
        remErrorsBtn = new QPushButton(game);
        remErrorsBtn->setObjectName("remErrorsBtn");
        remErrorsBtn->setGeometry(QRect(850, 570, 171, 41));
        QFont font4;
        font4.setPointSize(12);
        remErrorsBtn->setFont(font4);
        newGameBtn = new QPushButton(game);
        newGameBtn->setObjectName("newGameBtn");
        newGameBtn->setGeometry(QRect(830, 310, 251, 91));
        QFont font5;
        font5.setFamilies({QString::fromUtf8("MV Boli")});
        font5.setPointSize(30);
        newGameBtn->setFont(font5);
        eraseBtn = new QPushButton(game);
        eraseBtn->setObjectName("eraseBtn");
        eraseBtn->setGeometry(QRect(340, 820, 131, 61));
        eraseBtn->setFont(font2);
        grid4 = new QPushButton(game);
        grid4->setObjectName("grid4");
        grid4->setGeometry(QRect(320, 50, 51, 51));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Button, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid4->setPalette(palette3);
        grid4->setFont(font1);
        grid4->setAutoFillBackground(true);
        grid4->setAutoDefault(false);
        grid4->setFlat(true);
        grid5 = new QPushButton(game);
        grid5->setObjectName("grid5");
        grid5->setGeometry(QRect(390, 50, 51, 51));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::Button, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid5->setPalette(palette4);
        grid5->setFont(font1);
        grid5->setAutoFillBackground(true);
        grid5->setAutoDefault(false);
        grid5->setFlat(true);
        grid6 = new QPushButton(game);
        grid6->setObjectName("grid6");
        grid6->setGeometry(QRect(460, 50, 51, 51));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::Button, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid6->setPalette(palette5);
        grid6->setFont(font1);
        grid6->setAutoFillBackground(true);
        grid6->setAutoDefault(false);
        grid6->setFlat(true);
        grid7 = new QPushButton(game);
        grid7->setObjectName("grid7");
        grid7->setGeometry(QRect(550, 50, 51, 51));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::Button, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid7->setPalette(palette6);
        grid7->setFont(font1);
        grid7->setAutoFillBackground(true);
        grid7->setAutoDefault(false);
        grid7->setFlat(true);
        grid8 = new QPushButton(game);
        grid8->setObjectName("grid8");
        grid8->setGeometry(QRect(620, 50, 51, 51));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::Button, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid8->setPalette(palette7);
        grid8->setFont(font1);
        grid8->setAutoFillBackground(true);
        grid8->setAutoDefault(false);
        grid8->setFlat(true);
        grid9 = new QPushButton(game);
        grid9->setObjectName("grid9");
        grid9->setGeometry(QRect(690, 50, 51, 51));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::Button, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid9->setPalette(palette8);
        grid9->setFont(font1);
        grid9->setAutoFillBackground(true);
        grid9->setAutoDefault(false);
        grid9->setFlat(true);
        verticleLine1 = new QFrame(game);
        verticleLine1->setObjectName("verticleLine1");
        verticleLine1->setGeometry(QRect(290, 30, 16, 691));
        verticleLine1->setAutoFillBackground(false);
        verticleLine1->setStyleSheet(QString::fromUtf8(""));
        verticleLine1->setFrameShadow(QFrame::Plain);
        verticleLine1->setLineWidth(3);
        verticleLine1->setMidLineWidth(0);
        verticleLine1->setFrameShape(QFrame::VLine);
        verticleLine2 = new QFrame(game);
        verticleLine2->setObjectName("verticleLine2");
        verticleLine2->setGeometry(QRect(520, 30, 16, 691));
        verticleLine2->setAutoFillBackground(false);
        verticleLine2->setStyleSheet(QString::fromUtf8(""));
        verticleLine2->setFrameShadow(QFrame::Plain);
        verticleLine2->setLineWidth(3);
        verticleLine2->setMidLineWidth(0);
        verticleLine2->setFrameShape(QFrame::VLine);
        grid12 = new QPushButton(game);
        grid12->setObjectName("grid12");
        grid12->setGeometry(QRect(230, 120, 51, 51));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::Button, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid12->setPalette(palette9);
        grid12->setFont(font1);
        grid12->setAutoFillBackground(true);
        grid12->setAutoDefault(false);
        grid12->setFlat(true);
        grid10 = new QPushButton(game);
        grid10->setObjectName("grid10");
        grid10->setGeometry(QRect(90, 120, 51, 51));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::Button, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid10->setPalette(palette10);
        grid10->setFont(font1);
        grid10->setAutoFillBackground(true);
        grid10->setAutoDefault(false);
        grid10->setFlat(true);
        grid11 = new QPushButton(game);
        grid11->setObjectName("grid11");
        grid11->setGeometry(QRect(160, 120, 51, 51));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::Button, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid11->setPalette(palette11);
        grid11->setFont(font1);
        grid11->setAutoFillBackground(true);
        grid11->setAutoDefault(false);
        grid11->setFlat(true);
        grid13 = new QPushButton(game);
        grid13->setObjectName("grid13");
        grid13->setGeometry(QRect(320, 120, 51, 51));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::Button, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid13->setPalette(palette12);
        grid13->setFont(font1);
        grid13->setAutoFillBackground(true);
        grid13->setAutoDefault(false);
        grid13->setFlat(true);
        grid14 = new QPushButton(game);
        grid14->setObjectName("grid14");
        grid14->setGeometry(QRect(390, 120, 51, 51));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::Button, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid14->setPalette(palette13);
        grid14->setFont(font1);
        grid14->setAutoFillBackground(true);
        grid14->setAutoDefault(false);
        grid14->setFlat(true);
        grid15 = new QPushButton(game);
        grid15->setObjectName("grid15");
        grid15->setGeometry(QRect(460, 120, 51, 51));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::Button, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid15->setPalette(palette14);
        grid15->setFont(font1);
        grid15->setAutoFillBackground(true);
        grid15->setAutoDefault(false);
        grid15->setFlat(true);
        grid17 = new QPushButton(game);
        grid17->setObjectName("grid17");
        grid17->setGeometry(QRect(620, 120, 51, 51));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::Button, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid17->setPalette(palette15);
        grid17->setFont(font1);
        grid17->setAutoFillBackground(true);
        grid17->setAutoDefault(false);
        grid17->setFlat(true);
        grid16 = new QPushButton(game);
        grid16->setObjectName("grid16");
        grid16->setGeometry(QRect(550, 120, 51, 51));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::Button, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid16->setPalette(palette16);
        grid16->setFont(font1);
        grid16->setAutoFillBackground(true);
        grid16->setAutoDefault(false);
        grid16->setFlat(true);
        grid18 = new QPushButton(game);
        grid18->setObjectName("grid18");
        grid18->setGeometry(QRect(690, 120, 51, 51));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::Button, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid18->setPalette(palette17);
        grid18->setFont(font1);
        grid18->setAutoFillBackground(true);
        grid18->setAutoDefault(false);
        grid18->setFlat(true);
        grid20 = new QPushButton(game);
        grid20->setObjectName("grid20");
        grid20->setGeometry(QRect(160, 190, 51, 51));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::Button, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid20->setPalette(palette18);
        grid20->setFont(font1);
        grid20->setAutoFillBackground(true);
        grid20->setAutoDefault(false);
        grid20->setFlat(true);
        grid21 = new QPushButton(game);
        grid21->setObjectName("grid21");
        grid21->setGeometry(QRect(230, 190, 51, 51));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::Button, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette19.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid21->setPalette(palette19);
        grid21->setFont(font1);
        grid21->setAutoFillBackground(true);
        grid21->setAutoDefault(false);
        grid21->setFlat(true);
        grid19 = new QPushButton(game);
        grid19->setObjectName("grid19");
        grid19->setGeometry(QRect(90, 190, 51, 51));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::Button, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette20.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid19->setPalette(palette20);
        grid19->setFont(font1);
        grid19->setAutoFillBackground(true);
        grid19->setAutoDefault(false);
        grid19->setFlat(true);
        grid23 = new QPushButton(game);
        grid23->setObjectName("grid23");
        grid23->setGeometry(QRect(390, 190, 51, 51));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::Button, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette21.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid23->setPalette(palette21);
        grid23->setFont(font1);
        grid23->setAutoFillBackground(true);
        grid23->setAutoDefault(false);
        grid23->setFlat(true);
        grid22 = new QPushButton(game);
        grid22->setObjectName("grid22");
        grid22->setGeometry(QRect(320, 190, 51, 51));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::Button, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette22.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid22->setPalette(palette22);
        grid22->setFont(font1);
        grid22->setAutoFillBackground(true);
        grid22->setAutoDefault(false);
        grid22->setFlat(true);
        grid24 = new QPushButton(game);
        grid24->setObjectName("grid24");
        grid24->setGeometry(QRect(460, 190, 51, 51));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::Button, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid24->setPalette(palette23);
        grid24->setFont(font1);
        grid24->setAutoFillBackground(true);
        grid24->setAutoDefault(false);
        grid24->setFlat(true);
        grid26 = new QPushButton(game);
        grid26->setObjectName("grid26");
        grid26->setGeometry(QRect(620, 190, 51, 51));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::Button, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette24.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid26->setPalette(palette24);
        grid26->setFont(font1);
        grid26->setAutoFillBackground(true);
        grid26->setAutoDefault(false);
        grid26->setFlat(true);
        grid25 = new QPushButton(game);
        grid25->setObjectName("grid25");
        grid25->setGeometry(QRect(550, 190, 51, 51));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::Button, brush);
        palette25.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette25.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid25->setPalette(palette25);
        grid25->setFont(font1);
        grid25->setAutoFillBackground(true);
        grid25->setAutoDefault(false);
        grid25->setFlat(true);
        grid27 = new QPushButton(game);
        grid27->setObjectName("grid27");
        grid27->setGeometry(QRect(690, 190, 51, 51));
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::Button, brush);
        palette26.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette26.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid27->setPalette(palette26);
        grid27->setFont(font1);
        grid27->setAutoFillBackground(true);
        grid27->setAutoDefault(false);
        grid27->setFlat(true);
        line = new QFrame(game);
        line->setObjectName("line");
        line->setGeometry(QRect(80, 250, 671, 20));
        line->setFrameShadow(QFrame::Plain);
        line->setLineWidth(3);
        line->setFrameShape(QFrame::HLine);
        verticleLine2_2 = new QFrame(game);
        verticleLine2_2->setObjectName("verticleLine2_2");
        verticleLine2_2->setGeometry(QRect(140, 30, 20, 221));
        verticleLine2_2->setAutoFillBackground(false);
        verticleLine2_2->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_2->setFrameShadow(QFrame::Plain);
        verticleLine2_2->setLineWidth(1);
        verticleLine2_2->setMidLineWidth(0);
        verticleLine2_2->setFrameShape(QFrame::VLine);
        line_2 = new QFrame(game);
        line_2->setObjectName("line_2");
        line_2->setGeometry(QRect(80, 100, 211, 20));
        line_2->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_2->setFrameShadow(QFrame::Plain);
        line_2->setFrameShape(QFrame::HLine);
        grid38 = new QPushButton(game);
        grid38->setObjectName("grid38");
        grid38->setGeometry(QRect(160, 350, 51, 51));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::Button, brush);
        palette27.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette27.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid38->setPalette(palette27);
        grid38->setFont(font1);
        grid38->setAutoFillBackground(true);
        grid38->setAutoDefault(false);
        grid38->setFlat(true);
        grid48 = new QPushButton(game);
        grid48->setObjectName("grid48");
        grid48->setGeometry(QRect(230, 420, 51, 51));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::Button, brush);
        palette28.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette28.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid48->setPalette(palette28);
        grid48->setFont(font1);
        grid48->setAutoFillBackground(true);
        grid48->setAutoDefault(false);
        grid48->setFlat(true);
        grid46 = new QPushButton(game);
        grid46->setObjectName("grid46");
        grid46->setGeometry(QRect(90, 420, 51, 51));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::Button, brush);
        palette29.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette29.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid46->setPalette(palette29);
        grid46->setFont(font1);
        grid46->setAutoFillBackground(true);
        grid46->setAutoDefault(false);
        grid46->setFlat(true);
        grid30 = new QPushButton(game);
        grid30->setObjectName("grid30");
        grid30->setGeometry(QRect(230, 280, 51, 51));
        QPalette palette30;
        palette30.setBrush(QPalette::Active, QPalette::Button, brush);
        palette30.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette30.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid30->setPalette(palette30);
        grid30->setFont(font1);
        grid30->setAutoFillBackground(true);
        grid30->setAutoDefault(false);
        grid30->setFlat(true);
        grid39 = new QPushButton(game);
        grid39->setObjectName("grid39");
        grid39->setGeometry(QRect(230, 350, 51, 51));
        QPalette palette31;
        palette31.setBrush(QPalette::Active, QPalette::Button, brush);
        palette31.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette31.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid39->setPalette(palette31);
        grid39->setFont(font1);
        grid39->setAutoFillBackground(true);
        grid39->setAutoDefault(false);
        grid39->setFlat(true);
        grid28 = new QPushButton(game);
        grid28->setObjectName("grid28");
        grid28->setGeometry(QRect(90, 280, 51, 51));
        QPalette palette32;
        palette32.setBrush(QPalette::Active, QPalette::Button, brush);
        palette32.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette32.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid28->setPalette(palette32);
        grid28->setFont(font1);
        grid28->setAutoFillBackground(true);
        grid28->setAutoDefault(false);
        grid28->setFlat(true);
        grid47 = new QPushButton(game);
        grid47->setObjectName("grid47");
        grid47->setGeometry(QRect(160, 420, 51, 51));
        QPalette palette33;
        palette33.setBrush(QPalette::Active, QPalette::Button, brush);
        palette33.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette33.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid47->setPalette(palette33);
        grid47->setFont(font1);
        grid47->setAutoFillBackground(true);
        grid47->setAutoDefault(false);
        grid47->setFlat(true);
        grid37 = new QPushButton(game);
        grid37->setObjectName("grid37");
        grid37->setGeometry(QRect(90, 350, 51, 51));
        QPalette palette34;
        palette34.setBrush(QPalette::Active, QPalette::Button, brush);
        palette34.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette34.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid37->setPalette(palette34);
        grid37->setFont(font1);
        grid37->setAutoFillBackground(true);
        grid37->setAutoDefault(false);
        grid37->setFlat(true);
        grid29 = new QPushButton(game);
        grid29->setObjectName("grid29");
        grid29->setGeometry(QRect(160, 280, 51, 51));
        QPalette palette35;
        palette35.setBrush(QPalette::Active, QPalette::Button, brush);
        palette35.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette35.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid29->setPalette(palette35);
        grid29->setFont(font1);
        grid29->setAutoFillBackground(true);
        grid29->setAutoDefault(false);
        grid29->setFlat(true);
        grid31 = new QPushButton(game);
        grid31->setObjectName("grid31");
        grid31->setGeometry(QRect(320, 280, 51, 51));
        QPalette palette36;
        palette36.setBrush(QPalette::Active, QPalette::Button, brush);
        palette36.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette36.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid31->setPalette(palette36);
        grid31->setFont(font1);
        grid31->setAutoFillBackground(true);
        grid31->setAutoDefault(false);
        grid31->setFlat(true);
        grid50 = new QPushButton(game);
        grid50->setObjectName("grid50");
        grid50->setGeometry(QRect(390, 420, 51, 51));
        QPalette palette37;
        palette37.setBrush(QPalette::Active, QPalette::Button, brush);
        palette37.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette37.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid50->setPalette(palette37);
        grid50->setFont(font1);
        grid50->setAutoFillBackground(true);
        grid50->setAutoDefault(false);
        grid50->setFlat(true);
        grid41 = new QPushButton(game);
        grid41->setObjectName("grid41");
        grid41->setGeometry(QRect(390, 350, 51, 51));
        QPalette palette38;
        palette38.setBrush(QPalette::Active, QPalette::Button, brush);
        palette38.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette38.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid41->setPalette(palette38);
        grid41->setFont(font1);
        grid41->setAutoFillBackground(true);
        grid41->setAutoDefault(false);
        grid41->setFlat(true);
        grid49 = new QPushButton(game);
        grid49->setObjectName("grid49");
        grid49->setGeometry(QRect(320, 420, 51, 51));
        QPalette palette39;
        palette39.setBrush(QPalette::Active, QPalette::Button, brush);
        palette39.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette39.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid49->setPalette(palette39);
        grid49->setFont(font1);
        grid49->setAutoFillBackground(true);
        grid49->setAutoDefault(false);
        grid49->setFlat(true);
        grid40 = new QPushButton(game);
        grid40->setObjectName("grid40");
        grid40->setGeometry(QRect(320, 350, 51, 51));
        QPalette palette40;
        palette40.setBrush(QPalette::Active, QPalette::Button, brush);
        palette40.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette40.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid40->setPalette(palette40);
        grid40->setFont(font1);
        grid40->setAutoFillBackground(true);
        grid40->setAutoDefault(false);
        grid40->setFlat(true);
        grid42 = new QPushButton(game);
        grid42->setObjectName("grid42");
        grid42->setGeometry(QRect(460, 350, 51, 51));
        QPalette palette41;
        palette41.setBrush(QPalette::Active, QPalette::Button, brush);
        palette41.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette41.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid42->setPalette(palette41);
        grid42->setFont(font1);
        grid42->setAutoFillBackground(true);
        grid42->setAutoDefault(false);
        grid42->setFlat(true);
        grid51 = new QPushButton(game);
        grid51->setObjectName("grid51");
        grid51->setGeometry(QRect(460, 420, 51, 51));
        QPalette palette42;
        palette42.setBrush(QPalette::Active, QPalette::Button, brush);
        palette42.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette42.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid51->setPalette(palette42);
        grid51->setFont(font1);
        grid51->setAutoFillBackground(true);
        grid51->setAutoDefault(false);
        grid51->setFlat(true);
        grid32 = new QPushButton(game);
        grid32->setObjectName("grid32");
        grid32->setGeometry(QRect(390, 280, 51, 51));
        QPalette palette43;
        palette43.setBrush(QPalette::Active, QPalette::Button, brush);
        palette43.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette43.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid32->setPalette(palette43);
        grid32->setFont(font1);
        grid32->setAutoFillBackground(true);
        grid32->setAutoDefault(false);
        grid32->setFlat(true);
        grid33 = new QPushButton(game);
        grid33->setObjectName("grid33");
        grid33->setGeometry(QRect(460, 280, 51, 51));
        QPalette palette44;
        palette44.setBrush(QPalette::Active, QPalette::Button, brush);
        palette44.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette44.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid33->setPalette(palette44);
        grid33->setFont(font1);
        grid33->setAutoFillBackground(true);
        grid33->setAutoDefault(false);
        grid33->setFlat(true);
        grid34 = new QPushButton(game);
        grid34->setObjectName("grid34");
        grid34->setGeometry(QRect(550, 280, 51, 51));
        QPalette palette45;
        palette45.setBrush(QPalette::Active, QPalette::Button, brush);
        palette45.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette45.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid34->setPalette(palette45);
        grid34->setFont(font1);
        grid34->setAutoFillBackground(true);
        grid34->setAutoDefault(false);
        grid34->setFlat(true);
        grid53 = new QPushButton(game);
        grid53->setObjectName("grid53");
        grid53->setGeometry(QRect(620, 420, 51, 51));
        QPalette palette46;
        palette46.setBrush(QPalette::Active, QPalette::Button, brush);
        palette46.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette46.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid53->setPalette(palette46);
        grid53->setFont(font1);
        grid53->setAutoFillBackground(true);
        grid53->setAutoDefault(false);
        grid53->setFlat(true);
        grid44 = new QPushButton(game);
        grid44->setObjectName("grid44");
        grid44->setGeometry(QRect(620, 350, 51, 51));
        QPalette palette47;
        palette47.setBrush(QPalette::Active, QPalette::Button, brush);
        palette47.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette47.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid44->setPalette(palette47);
        grid44->setFont(font1);
        grid44->setAutoFillBackground(true);
        grid44->setAutoDefault(false);
        grid44->setFlat(true);
        grid52 = new QPushButton(game);
        grid52->setObjectName("grid52");
        grid52->setGeometry(QRect(550, 420, 51, 51));
        QPalette palette48;
        palette48.setBrush(QPalette::Active, QPalette::Button, brush);
        palette48.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette48.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid52->setPalette(palette48);
        grid52->setFont(font1);
        grid52->setAutoFillBackground(true);
        grid52->setAutoDefault(false);
        grid52->setFlat(true);
        grid43 = new QPushButton(game);
        grid43->setObjectName("grid43");
        grid43->setGeometry(QRect(550, 350, 51, 51));
        QPalette palette49;
        palette49.setBrush(QPalette::Active, QPalette::Button, brush);
        palette49.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette49.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid43->setPalette(palette49);
        grid43->setFont(font1);
        grid43->setAutoFillBackground(true);
        grid43->setAutoDefault(false);
        grid43->setFlat(true);
        grid45 = new QPushButton(game);
        grid45->setObjectName("grid45");
        grid45->setGeometry(QRect(690, 350, 51, 51));
        QPalette palette50;
        palette50.setBrush(QPalette::Active, QPalette::Button, brush);
        palette50.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette50.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid45->setPalette(palette50);
        grid45->setFont(font1);
        grid45->setAutoFillBackground(true);
        grid45->setAutoDefault(false);
        grid45->setFlat(true);
        grid54 = new QPushButton(game);
        grid54->setObjectName("grid54");
        grid54->setGeometry(QRect(690, 420, 51, 51));
        QPalette palette51;
        palette51.setBrush(QPalette::Active, QPalette::Button, brush);
        palette51.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette51.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid54->setPalette(palette51);
        grid54->setFont(font1);
        grid54->setAutoFillBackground(true);
        grid54->setAutoDefault(false);
        grid54->setFlat(true);
        grid35 = new QPushButton(game);
        grid35->setObjectName("grid35");
        grid35->setGeometry(QRect(620, 280, 51, 51));
        QPalette palette52;
        palette52.setBrush(QPalette::Active, QPalette::Button, brush);
        palette52.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette52.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid35->setPalette(palette52);
        grid35->setFont(font1);
        grid35->setAutoFillBackground(true);
        grid35->setAutoDefault(false);
        grid35->setFlat(true);
        grid36 = new QPushButton(game);
        grid36->setObjectName("grid36");
        grid36->setGeometry(QRect(690, 280, 51, 51));
        QPalette palette53;
        palette53.setBrush(QPalette::Active, QPalette::Button, brush);
        palette53.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette53.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid36->setPalette(palette53);
        grid36->setFont(font1);
        grid36->setAutoFillBackground(true);
        grid36->setAutoDefault(false);
        grid36->setFlat(true);
        line_3 = new QFrame(game);
        line_3->setObjectName("line_3");
        line_3->setGeometry(QRect(80, 480, 671, 20));
        line_3->setFrameShadow(QFrame::Plain);
        line_3->setLineWidth(3);
        line_3->setFrameShape(QFrame::HLine);
        grid56 = new QPushButton(game);
        grid56->setObjectName("grid56");
        grid56->setGeometry(QRect(160, 510, 51, 51));
        QPalette palette54;
        palette54.setBrush(QPalette::Active, QPalette::Button, brush);
        palette54.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette54.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid56->setPalette(palette54);
        grid56->setFont(font1);
        grid56->setAutoFillBackground(true);
        grid56->setAutoDefault(false);
        grid56->setFlat(true);
        grid65 = new QPushButton(game);
        grid65->setObjectName("grid65");
        grid65->setGeometry(QRect(160, 580, 51, 51));
        QPalette palette55;
        palette55.setBrush(QPalette::Active, QPalette::Button, brush);
        palette55.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette55.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid65->setPalette(palette55);
        grid65->setFont(font1);
        grid65->setAutoFillBackground(true);
        grid65->setAutoDefault(false);
        grid65->setFlat(true);
        grid55 = new QPushButton(game);
        grid55->setObjectName("grid55");
        grid55->setGeometry(QRect(90, 510, 51, 51));
        QPalette palette56;
        palette56.setBrush(QPalette::Active, QPalette::Button, brush);
        palette56.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette56.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid55->setPalette(palette56);
        grid55->setFont(font1);
        grid55->setAutoFillBackground(true);
        grid55->setAutoDefault(false);
        grid55->setFlat(true);
        grid64 = new QPushButton(game);
        grid64->setObjectName("grid64");
        grid64->setGeometry(QRect(90, 580, 51, 51));
        QPalette palette57;
        palette57.setBrush(QPalette::Active, QPalette::Button, brush);
        palette57.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette57.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid64->setPalette(palette57);
        grid64->setFont(font1);
        grid64->setAutoFillBackground(true);
        grid64->setAutoDefault(false);
        grid64->setFlat(true);
        grid74 = new QPushButton(game);
        grid74->setObjectName("grid74");
        grid74->setGeometry(QRect(160, 650, 51, 51));
        QPalette palette58;
        palette58.setBrush(QPalette::Active, QPalette::Button, brush);
        palette58.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette58.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid74->setPalette(palette58);
        grid74->setFont(font1);
        grid74->setAutoFillBackground(true);
        grid74->setAutoDefault(false);
        grid74->setFlat(true);
        grid66 = new QPushButton(game);
        grid66->setObjectName("grid66");
        grid66->setGeometry(QRect(230, 580, 51, 51));
        QPalette palette59;
        palette59.setBrush(QPalette::Active, QPalette::Button, brush);
        palette59.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette59.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid66->setPalette(palette59);
        grid66->setFont(font1);
        grid66->setAutoFillBackground(true);
        grid66->setAutoDefault(false);
        grid66->setFlat(true);
        grid57 = new QPushButton(game);
        grid57->setObjectName("grid57");
        grid57->setGeometry(QRect(230, 510, 51, 51));
        QPalette palette60;
        palette60.setBrush(QPalette::Active, QPalette::Button, brush);
        palette60.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette60.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid57->setPalette(palette60);
        grid57->setFont(font1);
        grid57->setAutoFillBackground(true);
        grid57->setAutoDefault(false);
        grid57->setFlat(true);
        grid73 = new QPushButton(game);
        grid73->setObjectName("grid73");
        grid73->setGeometry(QRect(90, 650, 51, 51));
        QPalette palette61;
        palette61.setBrush(QPalette::Active, QPalette::Button, brush);
        palette61.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette61.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid73->setPalette(palette61);
        grid73->setFont(font1);
        grid73->setAutoFillBackground(true);
        grid73->setAutoDefault(false);
        grid73->setFlat(true);
        grid75 = new QPushButton(game);
        grid75->setObjectName("grid75");
        grid75->setGeometry(QRect(230, 650, 51, 51));
        QPalette palette62;
        palette62.setBrush(QPalette::Active, QPalette::Button, brush);
        palette62.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette62.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid75->setPalette(palette62);
        grid75->setFont(font1);
        grid75->setAutoFillBackground(true);
        grid75->setAutoDefault(false);
        grid75->setFlat(true);
        grid77 = new QPushButton(game);
        grid77->setObjectName("grid77");
        grid77->setGeometry(QRect(390, 650, 51, 51));
        QPalette palette63;
        palette63.setBrush(QPalette::Active, QPalette::Button, brush);
        palette63.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette63.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid77->setPalette(palette63);
        grid77->setFont(font1);
        grid77->setAutoFillBackground(true);
        grid77->setAutoDefault(false);
        grid77->setFlat(true);
        grid67 = new QPushButton(game);
        grid67->setObjectName("grid67");
        grid67->setGeometry(QRect(320, 580, 51, 51));
        QPalette palette64;
        palette64.setBrush(QPalette::Active, QPalette::Button, brush);
        palette64.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette64.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid67->setPalette(palette64);
        grid67->setFont(font1);
        grid67->setAutoFillBackground(true);
        grid67->setAutoDefault(false);
        grid67->setFlat(true);
        grid58 = new QPushButton(game);
        grid58->setObjectName("grid58");
        grid58->setGeometry(QRect(320, 510, 51, 51));
        QPalette palette65;
        palette65.setBrush(QPalette::Active, QPalette::Button, brush);
        palette65.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette65.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid58->setPalette(palette65);
        grid58->setFont(font1);
        grid58->setAutoFillBackground(true);
        grid58->setAutoDefault(false);
        grid58->setFlat(true);
        grid78 = new QPushButton(game);
        grid78->setObjectName("grid78");
        grid78->setGeometry(QRect(460, 650, 51, 51));
        QPalette palette66;
        palette66.setBrush(QPalette::Active, QPalette::Button, brush);
        palette66.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette66.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid78->setPalette(palette66);
        grid78->setFont(font1);
        grid78->setAutoFillBackground(true);
        grid78->setAutoDefault(false);
        grid78->setFlat(true);
        grid69 = new QPushButton(game);
        grid69->setObjectName("grid69");
        grid69->setGeometry(QRect(460, 580, 51, 51));
        QPalette palette67;
        palette67.setBrush(QPalette::Active, QPalette::Button, brush);
        palette67.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette67.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid69->setPalette(palette67);
        grid69->setFont(font1);
        grid69->setAutoFillBackground(true);
        grid69->setAutoDefault(false);
        grid69->setFlat(true);
        grid59 = new QPushButton(game);
        grid59->setObjectName("grid59");
        grid59->setGeometry(QRect(390, 510, 51, 51));
        QPalette palette68;
        palette68.setBrush(QPalette::Active, QPalette::Button, brush);
        palette68.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette68.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid59->setPalette(palette68);
        grid59->setFont(font1);
        grid59->setAutoFillBackground(true);
        grid59->setAutoDefault(false);
        grid59->setFlat(true);
        grid68 = new QPushButton(game);
        grid68->setObjectName("grid68");
        grid68->setGeometry(QRect(390, 580, 51, 51));
        QPalette palette69;
        palette69.setBrush(QPalette::Active, QPalette::Button, brush);
        palette69.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette69.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid68->setPalette(palette69);
        grid68->setFont(font1);
        grid68->setAutoFillBackground(true);
        grid68->setAutoDefault(false);
        grid68->setFlat(true);
        grid76 = new QPushButton(game);
        grid76->setObjectName("grid76");
        grid76->setGeometry(QRect(320, 650, 51, 51));
        QPalette palette70;
        palette70.setBrush(QPalette::Active, QPalette::Button, brush);
        palette70.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette70.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid76->setPalette(palette70);
        grid76->setFont(font1);
        grid76->setAutoFillBackground(true);
        grid76->setAutoDefault(false);
        grid76->setFlat(true);
        grid60 = new QPushButton(game);
        grid60->setObjectName("grid60");
        grid60->setGeometry(QRect(460, 510, 51, 51));
        QPalette palette71;
        palette71.setBrush(QPalette::Active, QPalette::Button, brush);
        palette71.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette71.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid60->setPalette(palette71);
        grid60->setFont(font1);
        grid60->setAutoFillBackground(true);
        grid60->setAutoDefault(false);
        grid60->setFlat(true);
        grid61 = new QPushButton(game);
        grid61->setObjectName("grid61");
        grid61->setGeometry(QRect(550, 510, 51, 51));
        QPalette palette72;
        palette72.setBrush(QPalette::Active, QPalette::Button, brush);
        palette72.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette72.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid61->setPalette(palette72);
        grid61->setFont(font1);
        grid61->setAutoFillBackground(true);
        grid61->setAutoDefault(false);
        grid61->setFlat(true);
        grid63 = new QPushButton(game);
        grid63->setObjectName("grid63");
        grid63->setGeometry(QRect(690, 510, 51, 51));
        QPalette palette73;
        palette73.setBrush(QPalette::Active, QPalette::Button, brush);
        palette73.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette73.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid63->setPalette(palette73);
        grid63->setFont(font1);
        grid63->setAutoFillBackground(true);
        grid63->setAutoDefault(false);
        grid63->setFlat(true);
        grid72 = new QPushButton(game);
        grid72->setObjectName("grid72");
        grid72->setGeometry(QRect(690, 580, 51, 51));
        QPalette palette74;
        palette74.setBrush(QPalette::Active, QPalette::Button, brush);
        palette74.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette74.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid72->setPalette(palette74);
        grid72->setFont(font1);
        grid72->setAutoFillBackground(true);
        grid72->setAutoDefault(false);
        grid72->setFlat(true);
        grid80 = new QPushButton(game);
        grid80->setObjectName("grid80");
        grid80->setGeometry(QRect(620, 650, 51, 51));
        QPalette palette75;
        palette75.setBrush(QPalette::Active, QPalette::Button, brush);
        palette75.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette75.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid80->setPalette(palette75);
        grid80->setFont(font1);
        grid80->setAutoFillBackground(true);
        grid80->setAutoDefault(false);
        grid80->setFlat(true);
        grid79 = new QPushButton(game);
        grid79->setObjectName("grid79");
        grid79->setGeometry(QRect(550, 650, 51, 51));
        QPalette palette76;
        palette76.setBrush(QPalette::Active, QPalette::Button, brush);
        palette76.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette76.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid79->setPalette(palette76);
        grid79->setFont(font1);
        grid79->setAutoFillBackground(true);
        grid79->setAutoDefault(false);
        grid79->setFlat(true);
        grid70 = new QPushButton(game);
        grid70->setObjectName("grid70");
        grid70->setGeometry(QRect(550, 580, 51, 51));
        QPalette palette77;
        palette77.setBrush(QPalette::Active, QPalette::Button, brush);
        palette77.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette77.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid70->setPalette(palette77);
        grid70->setFont(font1);
        grid70->setAutoFillBackground(true);
        grid70->setAutoDefault(false);
        grid70->setFlat(true);
        grid71 = new QPushButton(game);
        grid71->setObjectName("grid71");
        grid71->setGeometry(QRect(620, 580, 51, 51));
        QPalette palette78;
        palette78.setBrush(QPalette::Active, QPalette::Button, brush);
        palette78.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette78.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid71->setPalette(palette78);
        grid71->setFont(font1);
        grid71->setAutoFillBackground(true);
        grid71->setAutoDefault(false);
        grid71->setFlat(true);
        grid81 = new QPushButton(game);
        grid81->setObjectName("grid81");
        grid81->setGeometry(QRect(690, 650, 51, 51));
        QPalette palette79;
        palette79.setBrush(QPalette::Active, QPalette::Button, brush);
        palette79.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette79.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid81->setPalette(palette79);
        grid81->setFont(font1);
        grid81->setAutoFillBackground(true);
        grid81->setAutoDefault(false);
        grid81->setFlat(true);
        grid62 = new QPushButton(game);
        grid62->setObjectName("grid62");
        grid62->setGeometry(QRect(620, 510, 51, 51));
        QPalette palette80;
        palette80.setBrush(QPalette::Active, QPalette::Button, brush);
        palette80.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette80.setBrush(QPalette::Disabled, QPalette::Button, brush);
        grid62->setPalette(palette80);
        grid62->setFont(font1);
        grid62->setAutoFillBackground(true);
        grid62->setAutoDefault(false);
        grid62->setFlat(true);
        verticleLine2_4 = new QFrame(game);
        verticleLine2_4->setObjectName("verticleLine2_4");
        verticleLine2_4->setGeometry(QRect(210, 30, 20, 221));
        verticleLine2_4->setAutoFillBackground(false);
        verticleLine2_4->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_4->setFrameShadow(QFrame::Plain);
        verticleLine2_4->setLineWidth(1);
        verticleLine2_4->setMidLineWidth(0);
        verticleLine2_4->setFrameShape(QFrame::VLine);
        verticleLine2_5 = new QFrame(game);
        verticleLine2_5->setObjectName("verticleLine2_5");
        verticleLine2_5->setGeometry(QRect(370, 30, 20, 221));
        verticleLine2_5->setAutoFillBackground(false);
        verticleLine2_5->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_5->setFrameShadow(QFrame::Plain);
        verticleLine2_5->setLineWidth(1);
        verticleLine2_5->setMidLineWidth(0);
        verticleLine2_5->setFrameShape(QFrame::VLine);
        verticleLine2_6 = new QFrame(game);
        verticleLine2_6->setObjectName("verticleLine2_6");
        verticleLine2_6->setGeometry(QRect(440, 30, 20, 221));
        verticleLine2_6->setAutoFillBackground(false);
        verticleLine2_6->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_6->setFrameShadow(QFrame::Plain);
        verticleLine2_6->setLineWidth(1);
        verticleLine2_6->setMidLineWidth(0);
        verticleLine2_6->setFrameShape(QFrame::VLine);
        verticleLine2_7 = new QFrame(game);
        verticleLine2_7->setObjectName("verticleLine2_7");
        verticleLine2_7->setGeometry(QRect(600, 30, 20, 221));
        verticleLine2_7->setAutoFillBackground(false);
        verticleLine2_7->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_7->setFrameShadow(QFrame::Plain);
        verticleLine2_7->setLineWidth(1);
        verticleLine2_7->setMidLineWidth(0);
        verticleLine2_7->setFrameShape(QFrame::VLine);
        verticleLine2_8 = new QFrame(game);
        verticleLine2_8->setObjectName("verticleLine2_8");
        verticleLine2_8->setGeometry(QRect(670, 30, 20, 221));
        verticleLine2_8->setAutoFillBackground(false);
        verticleLine2_8->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_8->setFrameShadow(QFrame::Plain);
        verticleLine2_8->setLineWidth(1);
        verticleLine2_8->setMidLineWidth(0);
        verticleLine2_8->setFrameShape(QFrame::VLine);
        verticleLine2_10 = new QFrame(game);
        verticleLine2_10->setObjectName("verticleLine2_10");
        verticleLine2_10->setGeometry(QRect(210, 270, 20, 211));
        verticleLine2_10->setAutoFillBackground(false);
        verticleLine2_10->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_10->setFrameShadow(QFrame::Plain);
        verticleLine2_10->setLineWidth(1);
        verticleLine2_10->setMidLineWidth(0);
        verticleLine2_10->setFrameShape(QFrame::VLine);
        verticleLine2_11 = new QFrame(game);
        verticleLine2_11->setObjectName("verticleLine2_11");
        verticleLine2_11->setGeometry(QRect(140, 270, 20, 211));
        verticleLine2_11->setAutoFillBackground(false);
        verticleLine2_11->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_11->setFrameShadow(QFrame::Plain);
        verticleLine2_11->setLineWidth(1);
        verticleLine2_11->setMidLineWidth(0);
        verticleLine2_11->setFrameShape(QFrame::VLine);
        verticleLine2_12 = new QFrame(game);
        verticleLine2_12->setObjectName("verticleLine2_12");
        verticleLine2_12->setGeometry(QRect(370, 270, 20, 211));
        verticleLine2_12->setAutoFillBackground(false);
        verticleLine2_12->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_12->setFrameShadow(QFrame::Plain);
        verticleLine2_12->setLineWidth(1);
        verticleLine2_12->setMidLineWidth(0);
        verticleLine2_12->setFrameShape(QFrame::VLine);
        verticleLine2_13 = new QFrame(game);
        verticleLine2_13->setObjectName("verticleLine2_13");
        verticleLine2_13->setGeometry(QRect(440, 270, 20, 211));
        verticleLine2_13->setAutoFillBackground(false);
        verticleLine2_13->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_13->setFrameShadow(QFrame::Plain);
        verticleLine2_13->setLineWidth(1);
        verticleLine2_13->setMidLineWidth(0);
        verticleLine2_13->setFrameShape(QFrame::VLine);
        verticleLine2_14 = new QFrame(game);
        verticleLine2_14->setObjectName("verticleLine2_14");
        verticleLine2_14->setGeometry(QRect(600, 270, 20, 211));
        verticleLine2_14->setAutoFillBackground(false);
        verticleLine2_14->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_14->setFrameShadow(QFrame::Plain);
        verticleLine2_14->setLineWidth(1);
        verticleLine2_14->setMidLineWidth(0);
        verticleLine2_14->setFrameShape(QFrame::VLine);
        verticleLine2_15 = new QFrame(game);
        verticleLine2_15->setObjectName("verticleLine2_15");
        verticleLine2_15->setGeometry(QRect(670, 270, 20, 211));
        verticleLine2_15->setAutoFillBackground(false);
        verticleLine2_15->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_15->setFrameShadow(QFrame::Plain);
        verticleLine2_15->setLineWidth(1);
        verticleLine2_15->setMidLineWidth(0);
        verticleLine2_15->setFrameShape(QFrame::VLine);
        verticleLine2_16 = new QFrame(game);
        verticleLine2_16->setObjectName("verticleLine2_16");
        verticleLine2_16->setGeometry(QRect(140, 500, 20, 211));
        verticleLine2_16->setAutoFillBackground(false);
        verticleLine2_16->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_16->setFrameShadow(QFrame::Plain);
        verticleLine2_16->setLineWidth(1);
        verticleLine2_16->setMidLineWidth(0);
        verticleLine2_16->setFrameShape(QFrame::VLine);
        verticleLine2_17 = new QFrame(game);
        verticleLine2_17->setObjectName("verticleLine2_17");
        verticleLine2_17->setGeometry(QRect(210, 500, 20, 211));
        verticleLine2_17->setAutoFillBackground(false);
        verticleLine2_17->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_17->setFrameShadow(QFrame::Plain);
        verticleLine2_17->setLineWidth(1);
        verticleLine2_17->setMidLineWidth(0);
        verticleLine2_17->setFrameShape(QFrame::VLine);
        verticleLine2_18 = new QFrame(game);
        verticleLine2_18->setObjectName("verticleLine2_18");
        verticleLine2_18->setGeometry(QRect(370, 500, 20, 211));
        verticleLine2_18->setAutoFillBackground(false);
        verticleLine2_18->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_18->setFrameShadow(QFrame::Plain);
        verticleLine2_18->setLineWidth(1);
        verticleLine2_18->setMidLineWidth(0);
        verticleLine2_18->setFrameShape(QFrame::VLine);
        verticleLine2_19 = new QFrame(game);
        verticleLine2_19->setObjectName("verticleLine2_19");
        verticleLine2_19->setGeometry(QRect(440, 500, 20, 211));
        verticleLine2_19->setAutoFillBackground(false);
        verticleLine2_19->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_19->setFrameShadow(QFrame::Plain);
        verticleLine2_19->setLineWidth(1);
        verticleLine2_19->setMidLineWidth(0);
        verticleLine2_19->setFrameShape(QFrame::VLine);
        verticleLine2_20 = new QFrame(game);
        verticleLine2_20->setObjectName("verticleLine2_20");
        verticleLine2_20->setGeometry(QRect(600, 500, 20, 211));
        verticleLine2_20->setAutoFillBackground(false);
        verticleLine2_20->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_20->setFrameShadow(QFrame::Plain);
        verticleLine2_20->setLineWidth(1);
        verticleLine2_20->setMidLineWidth(0);
        verticleLine2_20->setFrameShape(QFrame::VLine);
        verticleLine2_21 = new QFrame(game);
        verticleLine2_21->setObjectName("verticleLine2_21");
        verticleLine2_21->setGeometry(QRect(670, 500, 20, 211));
        verticleLine2_21->setAutoFillBackground(false);
        verticleLine2_21->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        verticleLine2_21->setFrameShadow(QFrame::Plain);
        verticleLine2_21->setLineWidth(1);
        verticleLine2_21->setMidLineWidth(0);
        verticleLine2_21->setFrameShape(QFrame::VLine);
        line_4 = new QFrame(game);
        line_4->setObjectName("line_4");
        line_4->setGeometry(QRect(80, 170, 211, 20));
        line_4->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_4->setFrameShadow(QFrame::Plain);
        line_4->setFrameShape(QFrame::HLine);
        line_5 = new QFrame(game);
        line_5->setObjectName("line_5");
        line_5->setGeometry(QRect(310, 100, 211, 20));
        line_5->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_5->setFrameShadow(QFrame::Plain);
        line_5->setFrameShape(QFrame::HLine);
        line_6 = new QFrame(game);
        line_6->setObjectName("line_6");
        line_6->setGeometry(QRect(310, 170, 211, 20));
        line_6->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_6->setFrameShadow(QFrame::Plain);
        line_6->setFrameShape(QFrame::HLine);
        line_7 = new QFrame(game);
        line_7->setObjectName("line_7");
        line_7->setGeometry(QRect(540, 100, 211, 20));
        line_7->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_7->setFrameShadow(QFrame::Plain);
        line_7->setFrameShape(QFrame::HLine);
        line_8 = new QFrame(game);
        line_8->setObjectName("line_8");
        line_8->setGeometry(QRect(540, 170, 211, 20));
        line_8->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_8->setFrameShadow(QFrame::Plain);
        line_8->setFrameShape(QFrame::HLine);
        line_9 = new QFrame(game);
        line_9->setObjectName("line_9");
        line_9->setGeometry(QRect(80, 330, 211, 20));
        line_9->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_9->setFrameShadow(QFrame::Plain);
        line_9->setFrameShape(QFrame::HLine);
        line_10 = new QFrame(game);
        line_10->setObjectName("line_10");
        line_10->setGeometry(QRect(80, 400, 211, 20));
        line_10->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_10->setFrameShadow(QFrame::Plain);
        line_10->setFrameShape(QFrame::HLine);
        line_11 = new QFrame(game);
        line_11->setObjectName("line_11");
        line_11->setGeometry(QRect(310, 330, 211, 20));
        line_11->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_11->setFrameShadow(QFrame::Plain);
        line_11->setFrameShape(QFrame::HLine);
        line_12 = new QFrame(game);
        line_12->setObjectName("line_12");
        line_12->setGeometry(QRect(310, 400, 211, 20));
        line_12->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_12->setFrameShadow(QFrame::Plain);
        line_12->setFrameShape(QFrame::HLine);
        line_13 = new QFrame(game);
        line_13->setObjectName("line_13");
        line_13->setGeometry(QRect(540, 330, 211, 20));
        line_13->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_13->setFrameShadow(QFrame::Plain);
        line_13->setFrameShape(QFrame::HLine);
        line_14 = new QFrame(game);
        line_14->setObjectName("line_14");
        line_14->setGeometry(QRect(540, 400, 211, 20));
        line_14->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_14->setFrameShadow(QFrame::Plain);
        line_14->setFrameShape(QFrame::HLine);
        line_15 = new QFrame(game);
        line_15->setObjectName("line_15");
        line_15->setGeometry(QRect(80, 560, 211, 20));
        line_15->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_15->setFrameShadow(QFrame::Plain);
        line_15->setFrameShape(QFrame::HLine);
        line_16 = new QFrame(game);
        line_16->setObjectName("line_16");
        line_16->setGeometry(QRect(80, 630, 211, 20));
        line_16->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_16->setFrameShadow(QFrame::Plain);
        line_16->setFrameShape(QFrame::HLine);
        line_17 = new QFrame(game);
        line_17->setObjectName("line_17");
        line_17->setGeometry(QRect(310, 560, 211, 20));
        line_17->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_17->setFrameShadow(QFrame::Plain);
        line_17->setFrameShape(QFrame::HLine);
        line_18 = new QFrame(game);
        line_18->setObjectName("line_18");
        line_18->setGeometry(QRect(310, 630, 211, 20));
        line_18->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_18->setFrameShadow(QFrame::Plain);
        line_18->setFrameShape(QFrame::HLine);
        line_19 = new QFrame(game);
        line_19->setObjectName("line_19");
        line_19->setGeometry(QRect(540, 560, 211, 20));
        line_19->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_19->setFrameShadow(QFrame::Plain);
        line_19->setFrameShape(QFrame::HLine);
        line_20 = new QFrame(game);
        line_20->setObjectName("line_20");
        line_20->setGeometry(QRect(540, 630, 211, 20));
        line_20->setStyleSheet(QString::fromUtf8("color: rgb(147, 147, 147);"));
        line_20->setFrameShadow(QFrame::Plain);
        line_20->setFrameShape(QFrame::HLine);

        retranslateUi(game);

        grid1->setDefault(false);
        grid2->setDefault(false);
        grid3->setDefault(false);
        grid4->setDefault(false);
        grid5->setDefault(false);
        grid6->setDefault(false);
        grid7->setDefault(false);
        grid8->setDefault(false);
        grid9->setDefault(false);
        grid12->setDefault(false);
        grid10->setDefault(false);
        grid11->setDefault(false);
        grid13->setDefault(false);
        grid14->setDefault(false);
        grid15->setDefault(false);
        grid17->setDefault(false);
        grid16->setDefault(false);
        grid18->setDefault(false);
        grid20->setDefault(false);
        grid21->setDefault(false);
        grid19->setDefault(false);
        grid23->setDefault(false);
        grid22->setDefault(false);
        grid24->setDefault(false);
        grid26->setDefault(false);
        grid25->setDefault(false);
        grid27->setDefault(false);
        grid38->setDefault(false);
        grid48->setDefault(false);
        grid46->setDefault(false);
        grid30->setDefault(false);
        grid39->setDefault(false);
        grid28->setDefault(false);
        grid47->setDefault(false);
        grid37->setDefault(false);
        grid29->setDefault(false);
        grid31->setDefault(false);
        grid50->setDefault(false);
        grid41->setDefault(false);
        grid49->setDefault(false);
        grid40->setDefault(false);
        grid42->setDefault(false);
        grid51->setDefault(false);
        grid32->setDefault(false);
        grid33->setDefault(false);
        grid34->setDefault(false);
        grid53->setDefault(false);
        grid44->setDefault(false);
        grid52->setDefault(false);
        grid43->setDefault(false);
        grid45->setDefault(false);
        grid54->setDefault(false);
        grid35->setDefault(false);
        grid36->setDefault(false);
        grid56->setDefault(false);
        grid65->setDefault(false);
        grid55->setDefault(false);
        grid64->setDefault(false);
        grid74->setDefault(false);
        grid66->setDefault(false);
        grid57->setDefault(false);
        grid73->setDefault(false);
        grid75->setDefault(false);
        grid77->setDefault(false);
        grid67->setDefault(false);
        grid58->setDefault(false);
        grid78->setDefault(false);
        grid69->setDefault(false);
        grid59->setDefault(false);
        grid68->setDefault(false);
        grid76->setDefault(false);
        grid60->setDefault(false);
        grid61->setDefault(false);
        grid63->setDefault(false);
        grid72->setDefault(false);
        grid80->setDefault(false);
        grid79->setDefault(false);
        grid70->setDefault(false);
        grid71->setDefault(false);
        grid81->setDefault(false);
        grid62->setDefault(false);


        QMetaObject::connectSlotsByName(game);
    } // setupUi

    void retranslateUi(QDialog *game)
    {
        game->setWindowTitle(QCoreApplication::translate("game", "Dialog", nullptr));
        QuitBtn->setText(QCoreApplication::translate("game", "Quit", nullptr));
        QuitAllBtn->setText(QCoreApplication::translate("game", "Quit All", nullptr));
        grid1->setText(QString());
        grid2->setText(QString());
        numOneBtn->setText(QCoreApplication::translate("game", "1", nullptr));
        numTwoBtn->setText(QCoreApplication::translate("game", "2", nullptr));
        numThreeBtn->setText(QCoreApplication::translate("game", "3", nullptr));
        numFourBtn->setText(QCoreApplication::translate("game", "4", nullptr));
        numFiveBtn->setText(QCoreApplication::translate("game", "5", nullptr));
        numSixBtn->setText(QCoreApplication::translate("game", "6", nullptr));
        numSevenBtn->setText(QCoreApplication::translate("game", "7", nullptr));
        numEightBtn->setText(QCoreApplication::translate("game", "8", nullptr));
        numNineBtn->setText(QCoreApplication::translate("game", "9", nullptr));
        submitBtn->setText(QCoreApplication::translate("game", "Submit board", nullptr));
        grid3->setText(QString());
        remErrorsBtn->setText(QCoreApplication::translate("game", "Remove Error Highlight", nullptr));
        newGameBtn->setText(QCoreApplication::translate("game", "New Game?", nullptr));
        eraseBtn->setText(QCoreApplication::translate("game", "Erase", nullptr));
        grid4->setText(QString());
        grid5->setText(QString());
        grid6->setText(QString());
        grid7->setText(QString());
        grid8->setText(QString());
        grid9->setText(QString());
        grid12->setText(QString());
        grid10->setText(QString());
        grid11->setText(QString());
        grid13->setText(QString());
        grid14->setText(QString());
        grid15->setText(QString());
        grid17->setText(QString());
        grid16->setText(QString());
        grid18->setText(QString());
        grid20->setText(QString());
        grid21->setText(QString());
        grid19->setText(QString());
        grid23->setText(QString());
        grid22->setText(QString());
        grid24->setText(QString());
        grid26->setText(QString());
        grid25->setText(QString());
        grid27->setText(QString());
        grid38->setText(QString());
        grid48->setText(QString());
        grid46->setText(QString());
        grid30->setText(QString());
        grid39->setText(QString());
        grid28->setText(QString());
        grid47->setText(QString());
        grid37->setText(QString());
        grid29->setText(QString());
        grid31->setText(QString());
        grid50->setText(QString());
        grid41->setText(QString());
        grid49->setText(QString());
        grid40->setText(QString());
        grid42->setText(QString());
        grid51->setText(QString());
        grid32->setText(QString());
        grid33->setText(QString());
        grid34->setText(QString());
        grid53->setText(QString());
        grid44->setText(QString());
        grid52->setText(QString());
        grid43->setText(QString());
        grid45->setText(QString());
        grid54->setText(QString());
        grid35->setText(QString());
        grid36->setText(QString());
        grid56->setText(QString());
        grid65->setText(QString());
        grid55->setText(QString());
        grid64->setText(QString());
        grid74->setText(QString());
        grid66->setText(QString());
        grid57->setText(QString());
        grid73->setText(QString());
        grid75->setText(QString());
        grid77->setText(QString());
        grid67->setText(QString());
        grid58->setText(QString());
        grid78->setText(QString());
        grid69->setText(QString());
        grid59->setText(QString());
        grid68->setText(QString());
        grid76->setText(QString());
        grid60->setText(QString());
        grid61->setText(QString());
        grid63->setText(QString());
        grid72->setText(QString());
        grid80->setText(QString());
        grid79->setText(QString());
        grid70->setText(QString());
        grid71->setText(QString());
        grid81->setText(QString());
        grid62->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class game: public Ui_game {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GAME_H
